/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StockAnalysis = IDL.Record({
  'rsi' : IDL.Float64,
  'currentPrice' : IDL.Float64,
  'macdSignal' : IDL.Float64,
  'entryPriceLow' : IDL.Float64,
  'signalScore' : IDL.Nat,
  'entryPriceHigh' : IDL.Float64,
  'targetPrice' : IDL.Float64,
  'quantitySuggestion' : IDL.Nat,
  'resistanceLevel' : IDL.Float64,
  'volumeRatio' : IDL.Float64,
  'profitProbability' : IDL.Nat,
  'sma20' : IDL.Float64,
  'sma50' : IDL.Float64,
  'supportLevel' : IDL.Float64,
  'analyzedAt' : IDL.Int,
  'stopLoss' : IDL.Float64,
  'change' : IDL.Float64,
  'recommendation' : IDL.Text,
  'exchange' : IDL.Text,
  'changePercent' : IDL.Float64,
  'symbol' : IDL.Text,
  'sma200' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PriceAlert = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'targetPrice' : IDL.Float64,
  'isTriggered' : IDL.Bool,
  'exchange' : IDL.Text,
  'symbol' : IDL.Text,
  'condition' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'riskLevel' : IDL.Text });
export const WatchlistItem = IDL.Record({
  'addedAt' : IDL.Int,
  'exchange' : IDL.Text,
  'symbol' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAlert' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addToWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'analyzeStock' : IDL.Func([IDL.Text, IDL.Text], [StockAnalysis], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAlerts' : IDL.Func([], [IDL.Vec(PriceAlert)], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(PriceAlert)], ['query']),
  'getAnalysisCache' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StockAnalysis)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRiskProfile' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAlert' : IDL.Func([IDL.Nat], [], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveRiskProfile' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StockAnalysis = IDL.Record({
    'rsi' : IDL.Float64,
    'currentPrice' : IDL.Float64,
    'macdSignal' : IDL.Float64,
    'entryPriceLow' : IDL.Float64,
    'signalScore' : IDL.Nat,
    'entryPriceHigh' : IDL.Float64,
    'targetPrice' : IDL.Float64,
    'quantitySuggestion' : IDL.Nat,
    'resistanceLevel' : IDL.Float64,
    'volumeRatio' : IDL.Float64,
    'profitProbability' : IDL.Nat,
    'sma20' : IDL.Float64,
    'sma50' : IDL.Float64,
    'supportLevel' : IDL.Float64,
    'analyzedAt' : IDL.Int,
    'stopLoss' : IDL.Float64,
    'change' : IDL.Float64,
    'recommendation' : IDL.Text,
    'exchange' : IDL.Text,
    'changePercent' : IDL.Float64,
    'symbol' : IDL.Text,
    'sma200' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PriceAlert = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'targetPrice' : IDL.Float64,
    'isTriggered' : IDL.Bool,
    'exchange' : IDL.Text,
    'symbol' : IDL.Text,
    'condition' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'riskLevel' : IDL.Text });
  const WatchlistItem = IDL.Record({
    'addedAt' : IDL.Int,
    'exchange' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAlert' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addToWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'analyzeStock' : IDL.Func([IDL.Text, IDL.Text], [StockAnalysis], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAlerts' : IDL.Func([], [IDL.Vec(PriceAlert)], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(PriceAlert)], ['query']),
    'getAnalysisCache' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StockAnalysis)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRiskProfile' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistItem)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAlert' : IDL.Func([IDL.Nat], [], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveRiskProfile' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };