/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PriceAlert {
  'id' : bigint,
  'createdAt' : bigint,
  'targetPrice' : number,
  'isTriggered' : boolean,
  'exchange' : string,
  'symbol' : string,
  'condition' : string,
}
export interface StockAnalysis {
  'rsi' : number,
  'currentPrice' : number,
  'macdSignal' : number,
  'entryPriceLow' : number,
  'signalScore' : bigint,
  'entryPriceHigh' : number,
  'targetPrice' : number,
  'quantitySuggestion' : bigint,
  'resistanceLevel' : number,
  'volumeRatio' : number,
  'profitProbability' : bigint,
  'sma20' : number,
  'sma50' : number,
  'supportLevel' : number,
  'analyzedAt' : bigint,
  'stopLoss' : number,
  'change' : number,
  'recommendation' : string,
  'exchange' : string,
  'changePercent' : number,
  'symbol' : string,
  'sma200' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'riskLevel' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WatchlistItem {
  'addedAt' : bigint,
  'exchange' : string,
  'symbol' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAlert' : ActorMethod<[string, string, number, string], bigint>,
  'addToWatchlist' : ActorMethod<[string, string], undefined>,
  'analyzeStock' : ActorMethod<[string, string], StockAnalysis>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAlerts' : ActorMethod<[], Array<PriceAlert>>,
  'getAlerts' : ActorMethod<[], Array<PriceAlert>>,
  'getAnalysisCache' : ActorMethod<[string], [] | [StockAnalysis]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRiskProfile' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchlist' : ActorMethod<[], Array<WatchlistItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAlert' : ActorMethod<[bigint], undefined>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveRiskProfile' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];